name: ozon
services:
    db:
        build:
          context: ./postgres_db
        container_name: ozon-db
        restart: always
        env_file:
          - .env
        ports:
          - ${LOCAL_PORT}:5432
        volumes:
          - ./postgres_db/init_scripts:/docker-entrypoint-initdb.d
          - db-data:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U ${CREATOR_USER} -d ${DB_NAME}" ]
          interval: 5s
          retries: 10
          timeout: 3s
    db_migrations:
      image: flyway/flyway:latest
      command: -url=jdbc:postgresql://db:5432/${DB_NAME} -user=${CREATOR_USER} -password=${CREATOR_PASSWORD} -placeholders.SEED_COUNT=${SEED_COUNT} -placeholders.APP_ENV=${APP_ENV} -target=${MIGRATION_VERSION:-latest} migrate
      env_file:
        - .env
      volumes:
        - ./flyway/migrations:/flyway/sql
      depends_on:
         db:
          condition: service_healthy

volumes:
    db-data: